- name: Install Apache and PHP packages
  apt:
    name: "{{ apache_packages }}"
    state: present
    update_cache: yes
  notify: restart apache

- name: Copy index.php
  copy:
    content: "<?php phpinfo(); ?>"
    dest: /var/www/html/index.php
